{{- if .Values.database.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "task-management.fullname" . }}-postgres-pvc
  namespace: {{ .Release.Namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.database.storageClass }}
  resources:
    requests:
      storage: {{ .Values.database.pvcSize }}
{{- end }}
