apiVersion: v1
kind: Secret
metadata:
  name: {{ include "task-management.fullname" . }}-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  DB_PASSWORD: "{{ .Values.database.password }}"
  POSTGRES_PASSWORD: "{{ .Values.database.password }}"
  DB_USER: "{{ .Values.database.user }}"
  POSTGRES_USER: "{{ .Values.database.user }}"
  DB_NAME: "{{ .Values.database.dbName }}"
  POSTGRES_DB: "{{ .Values.database.dbName }}"
